# Copyright 2021 Don Beattie
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Project information
site_name: Open ABL Project
site_description: Open Source ABL Libraries
site_author: Don Beattie
site_url: https://github.com/pages/donbeattie/OpenABL

# Repository
repo_name:  donbeattie/OpenABL
repo_url: https://github.com/donbeattie/OpenABL
edit_uri: ""

# Theme and overrides, i.e. language partial
theme:
  name: material

# Page tree
nav:
  - Home: index.md
  - Libraries:
      - Kafka: libraries/kafka.md
      - System: libraries/system.md
  - Contributing:
      - How to Contribute: contributing/HowToContribute.md
      - MkDocs Docker: contributing/MkDocsDocker.md

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.tilde

# Copyright
copyright: "Copyright &copy; 2021 Don Beattie"

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
