#!/bin/sh

COMMAND="$1"
OPTIONS="$2 $3 $4 $5 $6"

case $COMMAND in
  version) docker run --rm -it -v ${PWD}:/docs squidfunk/mkdocs-material --version  ;;
  serve)   docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material  ;;
  build)   docker run --rm -it -v ${PWD}:/docs squidfunk/mkdocs-material build $OPTIONS  ;;
  deploy)  docker run --rm -it -v ~/.ssh:/root/.ssh -v ${PWD}:/docs squidfunk/mkdocs-material gh-deploy --force  ;;
  new)     docker run --rm -it -v ${PWD}:/docs squidfunk/mkdocs-material new .  ;;
  * )      echo "\033[1mNAME\033[0m"
           echo "  \033[1mmd\033[0m - Command shortcut for MkDocs running under Docker"
           echo ""
           echo "\033[1mSYNOPSIS\033[0m"
           echo "  \033[1mmd\033[0m \033[4mcommand\033[0m"
           echo ""
           echo "\033[1mCOMMANDS\033[0m"
           echo "  Supply one of the following commands (in the root of a MkDocs project) to:"
           echo "    \033[1mhelp\033[0m    - Display this help syntax"
           echo "    \033[1mversion\033[0m - Display MkDocs and Python versions"
           echo "    \033[1mserve\033[0m   - Run the built-in development server at http://localhost:8000 (use control-c will stop the server)"
           echo "    \033[1mbuild\033[0m   - Build the MkDocs documentation"
           echo "    \033[1mdeploy\033[0m  - Deploy documentation to GitHub Pages"
           echo "    \033[1mnew\033[0m     - Create a new MkDocs project"
           echo ""
           exit 1 ;;
esac
